---
- name: OS agent logging functions on Windows
  hosts: all
  vars_files:
    - vars/commonvars.yml
    - vars/icamvars.yml
 
  tasks:
 
# tasks file for os_logging

  - fail: msg="'filelist', the list of files' name seperated by comma or 'all' is required"
    when: filelist is not defined

  - name:  Test if "{{ install_dir }}" directory exists on Windows
    win_stat:
      path:  "{{ install_dir }}"
    register: agentdir

  - name: ending the play if ITM dir does not exist
    meta: end_play
    when:
      - agentdir.stat.exists == false

# ------------------- get sample conf files from samples\logfile-monitoring to working_dir -------------------
  - name: get sample configuration file
    block:
      - fail: msg="'working_dir', the folder to store the sample configuration files is required"
        when: working_dir is not defined

      - name: get all sample configuration files from samples\logfile-monitoring
        win_copy:
          src: "{{ install_dir }}\\samples\\logfile-monitoring\\"
          dest: "{{working_dir}}\\"
          force: yes
          remote_src: yes
        when: (filelist | lower) == "all"

      - name: get specific sample configuration files from samples\logfile-monitoring
        win_copy:
          src: "{{ install_dir }}\\samples\\logfile-monitoring\\{{item}}"
          dest: "{{working_dir}}\\"
          force: yes
          remote_src: yes
        loop: "{{filelist.split(',')}}"
        when: (filelist | lower) != "all"
    when: (logging_type | lower) == "getsampleconfig"

# ------------------- get conf files from localconfig\nt\log_discovery to working_dir ------------------- 
  - name: get current configuration files
    block:
      - fail: msg="'working_dir', the folder to store the configuration files is required"
        when: working_dir is not defined
      
      - name: get all logging configuration files from localconfig\\nt\\log_discovery
        win_copy:
          src: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\"
          dest: "{{working_dir}}\\"
          force: yes
          remote_src: yes
        when: (filelist | lower) == "all"
      
      - name: get specific logging configuration files from localconfig\\nt\\log_discovery
        win_copy:
          src: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\{{item}}"
          dest: "{{working_dir}}\\"
          force: yes
          remote_src: yes
        loop: "{{filelist.split(',')}}"
        when: (filelist | lower) != "all"
    when: (logging_type | lower) == "getconfig"

# ------------------- distribute conf files from working_dir to localconfig\nt\log_discovery ------------------- 
  - name: distribute .fmt and .conf configuration files
    block:
      - fail: msg="'working_dir', the folder of the customized configuration files is required"
        when: working_dir is not defined

      - name: distribute all .fmt and .conf configuration files
        block:
          - name: find all .fmt and .conf configuration files
            win_find:
              paths: "{{ working_dir }}"
              patterns: [ '*.fmt', '*.conf' ]
            register: filestodis
          
          - name: copy all .fmt and .conf configuration files
            win_copy:
              src: "{{ item.path }}"
              dest: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\"
              force: yes
              remote_src: yes
            loop: "{{ filestodis.files }}"
        when: (filelist | lower) == "all"
      
      - name: distribute specify .fmt and .conf configuration files
        win_copy:
          src: "{{ working_dir }}\\{{item}}"
          dest: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\"
          force: yes
          remote_src: yes
        loop: "{{filelist.split(',')}}"
        when: (filelist | lower) != "all"
    when: (logging_type | lower) == "distribute"

# ------------------- undistribute conf files from localconfig\nt\log_discovery ------------------- 
  - name: undistribute .fmt and .conf configuration files
    block:
      - name: undistribute all .fmt and .conf configuration files
        block:
          - name: find all .fmt and .conf configuration files
            win_find:
              paths: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\"
              patterns: [ '*.fmt', '*.conf' ]
            register: filestoundis
          
          - name: delete all .fmt and .conf configuration files
            win_file:
              path: "{{ item.path }}"
              state: absent
            loop: "{{ filestoundis.files }}"
        when: (filelist | lower) == "all"
      
      - name: undistribute specific .fmt and .conf configuration files
        win_file:
          path: "{{ install_dir }}\\localconfig\\nt\\log_discovery\\{{item}}"
          state: absent
        loop: "{{filelist.split(',')}}"
        when: (filelist | lower) != "all"
    when: (logging_type | lower) == "undistribute"
